#!/usr/bin/env bun
/**
 * Atomic idempotent build script
 * 1. Builds Svelte dashboard -> dashboard/build/
 * 2. Generates embedded assets -> src/dashboard-assets.ts
 * 3. Bundles src/ -> .build/bundle.js -> dist/transcription-*
 */

import { readdir } from "node:fs/promises";
import { join, relative } from "node:path";
import { $ } from "bun";

const TARGETS = {
  "mac-arm64": "bun-darwin-arm64",
  "mac-x64": "bun-darwin-x64",
  "linux-x64": "bun-linux-x64",
  "linux-arm64": "bun-linux-arm64",
  "win-x64": "bun-windows-x64",
  // win-arm64 not supported by Bun yet: https://github.com/oven-sh/bun/issues/9824
} as const;

type Target = keyof typeof TARGETS;

// =============================================================================
// BUILD DASHBOARD (Svelte)
// =============================================================================

async function buildDashboard(): Promise<void> {
  console.log("Building dashboard...");
  await $`cd dashboard && bun run build`.quiet();
}

// =============================================================================
// GENERATE EMBEDDED ASSETS
// =============================================================================

async function* walkDir(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walkDir(path);
    } else {
      yield path;
    }
  }
}

function getMimeType(path: string): string {
  const ext = path.split(".").pop()?.toLowerCase();
  const mimeTypes: Record<string, string> = {
    html: "text/html; charset=utf-8",
    css: "text/css; charset=utf-8",
    js: "application/javascript; charset=utf-8",
    json: "application/json",
    svg: "image/svg+xml",
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    ico: "image/x-icon",
    woff: "font/woff",
    woff2: "font/woff2",
    txt: "text/plain",
  };
  return mimeTypes[ext || ""] || "application/octet-stream";
}

async function generateAssets(): Promise<void> {
  console.log("Generating embedded assets...");

  const buildDir = "dashboard/build";
  const assets: { route: string; mime: string; content: string }[] = [];

  for await (const filePath of walkDir(buildDir)) {
    const route = "/" + relative(buildDir, filePath);
    const mime = getMimeType(filePath);
    const content = await Bun.file(filePath).text();

    // Escape backticks and ${} for template literal
    const escaped = content
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`")
      .replace(/\$\{/g, "\\${");

    assets.push({ route, mime, content: escaped });
  }

  // Generate TypeScript file
  const code = `// AUTO-GENERATED - DO NOT EDIT
// Generated by build.ts from dashboard/build/

export interface Asset {
  content: string;
  mime: string;
}

export const DASHBOARD_ASSETS: Record<string, Asset> = {
${assets.map((a) => `  "${a.route}": { content: \`${a.content}\`, mime: "${a.mime}" },`).join("\n")}
};

export function getDashboardAsset(path: string): Asset | undefined {
  // Normalize path
  const normalized = path === "/" ? "/index.html" : path;
  return DASHBOARD_ASSETS[normalized];
}
`;

  await Bun.write("src/dashboard-assets.ts", code);
  console.log(`  Generated ${assets.length} embedded assets`);
}

// =============================================================================
// BUNDLE & COMPILE
// =============================================================================

async function bundle(): Promise<string> {
  const outfile = ".build/index.js";

  // Bundle all modules into single file
  const result = await Bun.build({
    entrypoints: ["src/index.ts"],
    outdir: ".build",
    target: "bun",
    minify: true,
    naming: "[name].[ext]",
  });

  if (!result.success) {
    console.error("Bundle failed:", result.logs);
    process.exit(1);
  }

  // Verify bundle exists
  const file = Bun.file(outfile);
  if (!(await file.exists())) {
    console.error("Bundle not created at", outfile);
    process.exit(1);
  }

  return outfile;
}

async function compile(bundlePath: string, target: Target): Promise<string> {
  const bunTarget = TARGETS[target];
  const ext = target.startsWith("win") ? ".exe" : "";
  const outfile = `dist/transcription-${target}${ext}`;

  // Compile bundle to standalone binary (without bytecode for compatibility)
  await $`bun build --compile --minify --target=${bunTarget} ${bundlePath} --outfile ${outfile}`.quiet();

  return outfile;
}

async function checksums(): Promise<void> {
  await $`cd dist && shasum -a 256 transcription-* > checksums.txt`.quiet();
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const requestedTarget = args[0] as Target | "all" | undefined;

  // Clean and create directories
  await $`rm -rf .build && mkdir -p .build dist`.quiet();

  // Build Svelte dashboard and generate embedded assets
  await buildDashboard();
  await generateAssets();

  console.log("Bundling...");
  const bundlePath = await bundle();

  const targets: Target[] =
    requestedTarget === "all" || !requestedTarget
      ? (Object.keys(TARGETS) as Target[])
      : [requestedTarget];

  // Validate target
  if (requestedTarget && requestedTarget !== "all" && !TARGETS[requestedTarget as Target]) {
    console.error(`Unknown target: ${requestedTarget}`);
    console.error(`Valid targets: ${Object.keys(TARGETS).join(", ")}, all`);
    process.exit(1);
  }

  // Compile for each target
  for (const target of targets) {
    console.log(`Compiling ${target}...`);
    await compile(bundlePath, target);
  }

  // Generate checksums if building all
  if (targets.length > 1) {
    console.log("Generating checksums...");
    await checksums();
  }

  // macOS universal binary
  if (targets.includes("mac-arm64") && targets.includes("mac-x64")) {
    console.log("Creating macOS universal binary...");
    await $`lipo -create dist/transcription-mac-x64 dist/transcription-mac-arm64 -output dist/transcription-mac-universal`.quiet();
  }

  // Cleanup
  await $`rm -rf .build`.quiet();

  console.log("\nDone!");
  await $`ls -lh dist/`;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
